In [3]:
import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)

In [5]:
pd.read_csv("train_features.csv")

,match_id_hash,game_time,game_mode,lobby_type,objectives_len,chat_len,r1_hero_id,r1_kills,r1_deaths,r1_assists,r1_denies,r1_gold,r1_lh,r1_xp,r1_health,r1_max_health,r1_max_mana,r1_level,r1_x,r1_y,r1_stuns,r1_creeps_stacked,r1_camps_stacked,r1_rune_pickups,r1_firstblood_claimed,r1_teamfight_participation,r1_towers_killed,r1_roshans_killed,r1_obs_placed,r1_sen_placed,r2_hero_id,r2_kills,r2_deaths,r2_assists,r2_denies,r2_gold,r2_lh,r2_xp,r2_health,r2_max_health,r2_max_mana,r2_level,r2_x,r2_y,r2_stuns,r2_creeps_stacked,r2_camps_stacked,r2_rune_pickups,r2_firstblood_claimed,r2_teamfight_participation,r2_towers_killed,r2_roshans_killed,r2_obs_placed,r2_sen_placed,r3_hero_id,r3_kills,r3_deaths,r3_assists,r3_denies,r3_gold,r3_lh,r3_xp,r3_health,r3_max_health,r3_max_mana,r3_level,r3_x,r3_y,r3_stuns,r3_creeps_stacked,r3_camps_stacked,r3_rune_pickups,r3_firstblood_claimed,r3_teamfight_participation,r3_towers_killed,r3_roshans_killed,r3_obs_placed,r3_sen_placed,r4_hero_id,r4_kills,r4_deaths,r4_assists,r4_denies,r4_gold,r4_lh,r4_xp,r4_health,r4_max_health,r4_max_mana,r4_level,r4_x,r4_y,r4_stuns,r4_creeps_stacked,r4_camps_stacked,r4_rune_pickups,r4_firstblood_claimed,r4_teamfight_participation,r4_towers_killed,r4_roshans_killed,r4_obs_placed,r4_sen_placed,r5_hero_id,r5_kills,r5_deaths,r5_assists,r5_denies,r5_gold,r5_lh,r5_xp,r5_health,r5_max_health,r5_max_mana,r5_level,r5_x,r5_y,r5_stuns,r5_creeps_stacked,r5_camps_stacked,r5_rune_pickups,r5_firstblood_claimed,r5_teamfight_participation,r5_towers_killed,r5_roshans_killed,r5_obs_placed,r5_sen_placed,d1_hero_id,d1_kills,d1_deaths,d1_assists,d1_denies,d1_gold,d1_lh,d1_xp,d1_health,d1_max_health,d1_max_mana,d1_level,d1_x,d1_y,d1_stuns,d1_creeps_stacked,d1_camps_stacked,d1_rune_pickups,d1_firstblood_claimed,d1_teamfight_participation,d1_towers_killed,d1_roshans_killed,d1_obs_placed,d1_sen_placed,d2_hero_id,d2_kills,d2_deaths,d2_assists,d2_denies,d2_gold,d2_lh,d2_xp,d2_health,d2_max_health,d2_max_mana,d2_level,d2_x,d2_y,d2_stuns,d2_creeps_stacked,d2_camps_stacked,d2_rune_pickups,d2_firstblood_claimed,d2_teamfight_participation,d2_towers_killed,d2_roshans_killed,d2_obs_placed,d2_sen_placed,d3_hero_id,d3_kills,d3_deaths,d3_assists,d3_denies,d3_gold,d3_lh,d3_xp,d3_health,d3_max_health,d3_max_mana,d3_level,d3_x,d3_y,d3_stuns,d3_creeps_stacked,d3_camps_stacked,d3_rune_pickups,d3_firstblood_claimed,d3_teamfight_participation,d3_towers_killed,d3_roshans_killed,d3_obs_placed,d3_sen_placed,d4_hero_id,d4_kills,d4_deaths,d4_assists,d4_denies,d4_gold,d4_lh,d4_xp,d4_health,d4_max_health,d4_max_mana,d4_level,d4_x,d4_y,d4_stuns,d4_creeps_stacked,d4_camps_stacked,d4_rune_pickups,d4_firstblood_claimed,d4_teamfight_participation,d4_towers_killed,d4_roshans_killed,d4_obs_placed,d4_sen_placed,d5_hero_id,d5_kills,d5_deaths,d5_assists,d5_denies,d5_gold,d5_lh,d5_xp,d5_health,d5_max_health,d5_max_mana,d5_level,d5_x,d5_y,d5_stuns,d5_creeps_stacked,d5_camps_stacked,d5_rune_pickups,d5_firstblood_claimed,d5_teamfight_participation,d5_towers_killed,d5_roshans_killed,d5_obs_placed,d5_sen_placed
0,a400b8f29dece5f4d266f49f1ae2e98a,155,22,7,1,11,11,0,0,0,0,543,7,533,358,600,350.93784,2,116,122,0.000000,0,0,1,0,0.000000,0,0,0,0,78,0,0,0,3,399,4,478,636,720,254.93774,2,124,126,0.000000,0,0,0,0,0.000000,0,0,0,0,14,0,1,0,0,304,0,130,700,700,242.93773,1,70,156,0.000000,0,0,1,0,0.000000,0,0,0,0,59,0,0,0,1,389,4,506,399,700,326.93780,2,170,86,0.000000,0,0,0,0,0.000000,0,0,0,0,77,0,0,0,0,402,10,344,422,800,314.93780,2,120,100,0.000000,0,0,0,0,0.000000,0,0,0,0,12,0,0,1,13,982,12,780,650,720,386.93787,3,82,170,0.000000,0,0,1,0,1.00000,0,0,0,0,21,0,0,0,6,788,9,706,640,640,422.93790,3,174,90,0.000000,0,0,2,0,0.00000,0,0,0,0,60,0,0,0,1,531,0,307,720,720,242.93773,2,180,84,0.299948,0,0,2,0,0.00000,0,0,0,0,84,1,0,0,0,796,0,421,760,760,326.93780,2,90,150,0.000000,0,0,2,1,1.000,0,0,1,0,34,0,0,0,0,851,11,870,593,680,566.93805,3,128,128,0.000000,0,0,0,0,0.0000,0,0,0,0
1,b9c57c450ce74a2af79c9ce96fac144d,658,4,0,3,10,15,7,2,0,7,5257,52,3937,1160,1160,566.93805,8,76,78,0.000000,0,0,0,0,0.437500,0,0,0,0,96,3,1,2,3,3394,19,3897,1352,1380,386.93787,8,78,166,8.397949,0,0,4,0,0.312500,0,0,0,0,27,1,1,4,2,2212,4,2561,710,860,530.93800,6,156,146,11.964951,2,1,4,0,0.312500,0,0,3,1,63,4,0,3,12,4206,38,4459,420,880,482.93796,9,154,148,0.000000,0,0,3,0,0.437500,0,0,1,2,89,1,0,5,4,3103,14,2712,856,900,446.93793,6,150,148,21.697395,0,0,2,0,0.375000,1,0,0,0,58,1,2,0,4,2823,24,3281,700,700,686.93820,7,88,170,3.165901,1,1,3,0,0.25000,0,0,1,0,14,1,6,0,1,2466,17,2360,758,1040,326.93780,6,156,98,0.066650,0,0,1,1,0.25000,0,0,4,2,1,1,3,1,7,3624,29,3418,485,800,350.93784,7,124,144,0.299955,2,1,4,0,0.50000,0,0,0,0,56,0,3,2,3,2808,18,2730,567,1160,410.93790,6,124,142,0.000000,0,0,6,0,0.500,0,0,0,0,92,0,2,0,1,1423,8,1136,800,800,446.93793,4,180,176,0.000000,0,0,0,0,0.0000,0,0,0,0
2,6db558535151ea18ca70a6892197db41,21,23,0,0,0,101,0,0,0,0,176,0,0,680,680,506.93800,1,118,118,0.000000,0,0,0,0,0.000000,0,0,0,0,51,0,0,0,0,176,0,0,720,720,278.93777,1,156,104,0.000000,0,0,0,0,0.000000,0,0,0,0,44,0,0,0,0,176,0,0,568,600,254.93774,1,78,144,0.000000,0,0,1,0,0.000000,0,0,0,0,49,0,0,0,0,176,0,0,580,580,254.93774,1,150,78,0.000000,0,0,1,0,0.000000,0,0,0,0,53,0,0,0,0,176,0,0,580,580,374.93787,1,78,142,0.000000,0,0,1,0,0.000000,0,0,0,0,18,0,0,0,0,96,0,0,660,660,266.93774,1,180,178,0.000000,0,0,0,0,0.00000,0,0,0,0,67,0,0,0,0,96,0,0,586,620,278.93777,1,100,174,0.000000,0,0,0,0,0.00000,0,0,0,0,47,0,0,0,0,96,0,0,660,660,290.93777,1,178,112,0.000000,0,0,1,0,0.00000,0,0,0,0,40,0,0,0,0,96,0,0,600,600,302.93777,1,176,110,0.000000,0,0,0,0,0.000,0,0,0,0,17,0,0,0,0,96,0,0,640,640,446.93793,1,162,162,0.000000,0,0,0,0,0.0000,0,0,0,0
3,46a0ddce8f7ed2a8d9bd5edcbb925682,576,22,7,1,4,14,1,0,3,1,1613,0,1471,900,900,290.93777,4,170,96,2.366089,0,0,5,0,0.571429,0,0,0,0,99,1,0,1,2,2816,30,3602,878,1100,494.93796,8,82,154,0.000000,0,0,1,0,0.285714,0,0,0,0,101,3,1,1,9,4017,44,4811,980,980,902.93835,9,126,128,0.000000,0,0,2,1,0.571429,0,0,2,0,26,1,1,2,1,1558,2,1228,640,640,422.93790,4,120,138,7.098264,0,0,5,0,0.428571,0,0,2,0,41,0,0,1,30,3344,55,3551,1079,1100,362.93784,7,176,94,1.932884,0,0,0,0,0.142857,0,0,0,0,18,0,0,0,0,2712,69,2503,825,1160,338.93784,6,94,158,0.000000,3,1,4,0,0.00000,0,0,0,0,98,1,3,0,5,2217,23,3310,735,880,506.93800,7,126,142,0.000000,0,0,1,0,0.50000,0,0,1,0,8,0,1,1,6,3035,44,2508,817,860,350.93784,6,78,160,0.000000,0,0,1,0,0.50000,0,0,0,0,69,0,2,0,0,2004,16,1644,1160,1160,386.93787,4,176,100,4.998863,0,0,2,0,0.000,0,0,0,0,86,0,1,0,1,1333,2,1878,630,740,518.93800,5,82,160,8.664527,3,1,3,0,0.0000,0,0,2,0
4,b1b35ff97723d9b7ade1c9c3cf48f770,453,22,7,1,3,42,0,1,1,0,1404,9,1351,1000,1000,338.93784,4,80,164,9.930903,0,0,4,0,0.500000,0,0,0,0,69,1,0,0,0,1840,14,1693,868,1000,350.93784,5,78,166,1.832892,0,0,0,1,0.500000,0,0,0,0,27,0,1,0,0,1204,10,3210,578,860,792.93823,7,120,122,3.499146,0,0,0,0,0.000000,0,0,0,0,104,0,0,2,0,1724,21,1964,777,980,434.93793,5,138,94,0.000000,0,0,1,0,1.000000,0,0,0,0,65,1,2,0,0,1907,8,1544,281,820,446.93793,4,174,100,0.000000,0,0,6,0,0.500000,0,0,0,0,23,1,0,0,0,1422,10,1933,709,940,362.93784,5,84,170,11.030720,0,0,1,0,0.25000,0,0,0,0,22,1,0,0,1,1457,12,1759,712,820,482.93796,5,174,106,2.199399,0,0,1,0,0.25000,0,0,0,0,35,0,0,1,2,2402,35,3544,349,720,434.93793,7,128,126,0.000000,0,0,2,0,0.25000,0,0,0,0,72,2,1,0,0,1697,12,1651,680,680,374.93787,4,176,108,13.596678,0,0,2,0,0.500,0,0,0,0,1,0,1,1,8,2199,32,1919,692,740,302.93777,5,104,162,0.000000,2,1,2,0,0.2500,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39670,defd0caeed6ea83d7d5fbdec013fe7d1,1783,22,0,8,23,3,1,9,9,0,6283,13,7847,0,1380,710.93820,13,144,100,90.944490,0,0,8,0,0.500000,0,0,10,19,49,2,7,8,7,8838,83,10815,1760,1760,530.93800,15,74,76,41.750020,0,0,2,0,0.500000,0,0,1,0,7,4,7,8,4,8530,66,9270,0,1580,1162.93860,14,140,98,71.732760,0,0,6,0,0.600000,0,0,0,0,74,8,3,2,27,14815,161,19257,0,1875,1581.93900,21,144,100,24.060377,0,0,4,0,0.500000,2,0,2,4,63,4,6,5,14,9864,91,10367,1000,1000,554.93805,15,140,138,0.000000,0,0,14,1,0.450000,1,0,0,0,14,6,7,11,6,9371,67,11911,0,2515,1275.93870,16,134,98,39.090730,0,0,6,0,0.53125,0,0,1,2,36,8,1,11,2,13071,143,16893,1560,1560,1356.93880,19,124,78,4.432127,0,0,7,0,0.59375,1,0,0,0,32,7,4,10,7,7937,25,10579,1120,1120,494.93796,15,124,164,0.000000,0,0,9,0,0.53125,0,0,3,2,8,10,5,6,21,15226,183,16164,1667,1680,602.93805,19,126,76,0.799805,0,0,9,0,0.500,2,0,0,0,5,1,4,17,0,6033,20,9742,1040,1040,830.93830,14,130,76,26.493834,6,2,3,0,0.5625,0,0,7,2
39671,bc7a87ed5f9c2bca55f9f7a93da0b0c5,377,22,7,1,0,14,0,2,1,1,809,2,1102,0,900,290.93777,4,84,156,1.266357,0,0,0,0,0.500000,0,0,0,0,80,1,1,0,6,1692,21,1323,627,680,278.93777,4,174,100,0.000000,0,0,0,0,0.500000,0,0,0,0,12,0,0,1,3,1671,22,2345,509,920,506.93800,6,112,114,0.000000,0,0,0,0,0.500000,0,0,0,0,3,1,0,1,2,1443,2,1150,761,840,458.93793,4,176,94,0.000000,3,1,6,1,1.000000,0,0,1,1,63,0,0,0,0,1173,9,1505,523,660,350.93784,4,86,156,0.000000,0,0,2,0,0.000000,0,0,0,1,88,0,1,1,2,1039,7,1097,700,700,374.93787,4,174,110,10.097570,0,0,1,0,0.50000,0,0,0,0,47,1,0,0,0,967,3,1154,573,800,350.93784,4,178,108,0.000000,0,0,0,0,0.50000,0,0,0,0,11,1,1,0,8,2184,29,2964,820,820,470.93796,7,120,122,0.000000,0,0,2,0,0.50000,0,0,0,0,27,0,0,0,6,1000,2,838,509,740,422.93790,3,84,156,6.298479,3,1,4,0,0.000,0,0,1,1,73,0,0,0,10,3203,41,2510,95,920,494.93796,6,90,158,0.000000,0,0,1,0,0.0000,0,0,0,0
39672,e2ca68ac1a6847f4a37f6c9c8ee8695b,643,22,7,1,23,63,1,4,0,2,1747,4,2677,369,780,422.93790,6,80,138,0.000000,0,0,4,0,0.250000,0,0,0,0,27,0,3,2,2,1331,2,1737,780,780,470.93796,5,164,96,26.693481,0,0,3,0,0.500000,0,0,3,0,110,0,10,1,0,1055,0,379,345,680,326.93780,2,106,110,0.000000,0,0,0,0,0.250000,0,0,0,0,10,3,2,0,15,4191,44,3760,440,640,374.93787,8,176,84,0.000000,0,0,3,0,0.750000,0,0,0,0,49,0,1,0,7,3028,44,3661,0,1360,410.93790,8,88,144,5.065430,0,0,0,0,0.000000,0,0,1,1,120,3,0,1,3,3148,27,2941,679,820,398.93787,7,174,90,-0.983398,0,0,2,0,0.20000,0,0,0,0,40,0,3,4,0,2208,10,1847,798,820,530.93800,5,174,90,0.000000,0,0,5,0,0.20000,0,0,0,0,30,3,1,2,4,2266,3,2620,465,760,554.93805,6,80,154,11.063930,3,1,6,0,0.25000,0,0,3,3,44,3,0,3,21,4453,48,4659,968,980,410.93790,9,82,154,0.000000,0,0,2,0,0.300,0,0,0,0,11,9,0,1,14,5431,51,5420,773,1000,686.93820,10,120,124,2.532715,0,0,3,1,0.5000,0,0,1,0
39673,47ad6454ede66c1c78fdaa9391dfc556,2405,22,7,12,4,22,3,8,14,7,14375,168,19847,0,1995,1843.93920,21,134,154,8.850186,0,0,15,0,0.404762,1,0,1,0,32,9,12,10,2,12448,42,18449,1343,1500,794.93823,21,130,150,0.000000,0,0,18,0,0.428571,0,0,1,1,81,8,3,9,7,21451,305,27114,5200,5200,854.93830,25,122,124,23.931118,0,0,8,0,0.404762,2,0,0,0,91,1,14,13,6,8134,11,13382,1280,1280,698.93820,17,94,132,0.000000,0,0,11,0,0.333333,0,0,14,2,23,21,3,7,15,32403,413,26950,1550,2760,902.93835,25,116,134,35.064312,0,0,10,0,0.666667,3,1,0,0,26,9,11,15,1,11499,20,18654,0,1820,1484.93900,21,120,138,132.343580,0,0,5,1,0.60000,0,0,13,4,53,6,12,17,1,19420,276,20634,0,1960,1574.93900,22,76,146,0.000000,0,0,1,0,0.57500,1,0,0,2,10,10,6,2,22,17934,236,22866,813,1500,722.93820,23,126,158,5.569586,0,0,10,0,0.30000,0,0,2,0,42,5,6,18,1,14477,136,19556,1657,2260,794.93823,21,118,164,40.033060,1,1,9,0,0.575,1,0,0,1,11,9,7,16,26,18231,181,25354,1840,2525,1548.93900,24,98,158,17.583984,3,1,4,0,0.6250,0,0,0,0
39674,9928dfde50efcbdb2055da23dcdbc101,1775,22,0,10,13,32,3,4,15,0,8847,20,11151,0,1100,602.93805,15,118,120,0.000000,0,0,16,0,0.600000,0,0,5,6,69,5,7,11,5,11458,102,10823,2267,2280,698.93820,15,174,112,32.059246,0,0,7,0,0.533333,1,0,0,0,76,10,0,5,29,16708,201,19598,2750,2750,1756.93920,21,178,110,46.655327,0,0,3,0,0.500000,2,0,0,0,10,2,5,7,2,13150,194,16362,1061,1200,614.93810,19,106,114,2.399467,1,1,6,0,0.300000,1,0,0,0,68,10,4,10,0,9666,48,13504,1440,1440,1380.93880,17,180,108,14.772326,2,1,2,0,0.666667,0,0,8,4,49,1,7,4,6,10347,105,11612,2180,2180,578.93805,16,178,166,22.585493,0,0,8,0,0.25000,2,0,0,0,110,4,10,5,4,9140,49,9222,0,1560,758.93823,14,122,126,4.432282,2,1,13,0,0.45000,0,0,9,8,62,4,4,10,3,8229,10,10008,528,1120,888.93835,14,140,134,0.928828,0,0,4,0,0.70000,0,0,1,0,106,8,3,6,15,14982,183,15506,1832,1840,1226.93870,19,78,166,36.424126,2,1,12,1,0.700,1,0,1,0,95,3,6,8,19,14096,225,15424,2031,2060,470.93796,19,104,162,8.331238,0,0,1,0,0.5500,1,0,0,0

In [7]:
 import json

In [11]:
import itertools

path = "DOTA 2//train_matches.jsonl"

with open(path, "r", encoding="utf-8") as f:
    for line in itertools.islice(f, 5):  # первые 5 строк
        print(line.strip())

{"game_time": 155, "match_id_hash": "a400b8f29dece5f4d266f49f1ae2e98a", "teamfights": [], "objectives": [{"time": 124.203, "type": "CHAT_MESSAGE_FIRSTBLOOD", "slot": 8, "key": 2, "player_slot": 131}], "chat": [{"player_slot": 0, "time": -13.63, "text": "???"}, {"player_slot": 0, "time": -10.964, "text": "? ???? ??????"}, {"player_slot": 0, "time": -7.965, "text": "???????? ????("}, {"player_slot": 4, "time": 43.756, "text": "???"}, {"player_slot": 2, "time": 44.422, "text": "??? ??????"}, {"player_slot": 4, "time": 45.289, "text": "*[*[*["}, {"player_slot": 2, "time": 46.622, "text": "????"}, {"player_slot": 4, "time": 47.355, "text": "??? ??????"}, {"player_slot": 4, "time": 48.688, "text": "????"}, {"player_slot": 2, "time": 52.021, "text": "???????? ??? ??????"}, {"player_slot": 4, "time": 73.349, "text": "????? ??? ?????"}], "game_mode": 22, "lobby_type": 7, "players": [{"player_slot": 0, "hero_id": 11, "hero_name": "npc_dota_hero_nevermore", "account_id_hash": "86bf86c5488742478688149155258ea8", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 94.977, "max": true, "inflictor": "nevermore_shadowraze2", "unit": "npc_dota_hero_nevermore", "key": "npc_dota_hero_tinker", "value": 136, "slot": 0, "player_slot": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 356], "lh_t": [0, 0, 4], "dn_t": [0, 0, 0], "xp_t": [0, 107, 387], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "wraith_band"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": -84.215, "key": "tango"}, {"time": 99.409, "key": "flask"}, {"time": 100.909, "key": "clarity"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 134.067, "key": 0}], "obs": {}, "sen": {}, "actions": {"1": 551, "2": 8, "4": 43, "6": 1, "7": 2, "8": 6, "10": 1, "11": 2, "15": 2, "16": 8, "17": 2, "19": 6, "21": 30, "33": 30}, "pings": {"0": 6}, "purchase": {"wraith_band": 1, "enchanted_mango": 1, "tpscroll": 1, "tango": 1, "flask": 1, "clarity": 1}, "gold_reasons": {"0": 600, "13": 308}, "xp_reasons": {"2": 533}, "killed": {"npc_dota_creep_badguys_melee": 250, "npc_dota_creep_badguys_ranged": 203}, "item_uses": {"tango": 1, "flask": 1}, "ability_uses": {"nevermore_shadowraze3": 1, "nevermore_shadowraze1": 1, "nevermore_shadowraze2": 1}, "hero_hits": {"null": 3, "nevermore_shadowraze3": 1, "nevermore_shadowraze1": 1, "nevermore_shadowraze2": 1}, "damage": {"npc_dota_creep_goodguys_melee": 92, "npc_dota_creep_badguys_melee": 478, "npc_dota_hero_tinker": 459, "npc_dota_creep_badguys_ranged": 203, "npc_dota_creep_goodguys_ranged": 55}, "damage_taken": {"npc_dota_hero_tinker": 704, "npc_dota_creep_badguys_melee": 231, "npc_dota_creep_badguys_ranged": 38}, "damage_inflictor": {"null": 159, "nevermore_shadowraze3": 64, "nevermore_shadowraze1": 100, "nevermore_shadowraze2": 136}, "runes": {"0": 1}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"tinker_laser": 410, "null": 294}, "randomed": false, "pred_vict": false, "gold": 543, "lh": 7, "xp": 533, "x": 116, "y": 122, "hero_inventory": [{"id": "item_tango", "num_charges": 2, "cooldown": 0}, {"id": "item_wraith_band", "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_clarity", "num_charges": 1, "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 358, "max_health": 600, "max_mana": 350.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 0, "nearby_creep_death_count": 19}, {"player_slot": 1, "hero_id": 78, "hero_name": "npc_dota_hero_brewmaster", "account_id_hash": "67d6d5d0a77e585a11319af7bdd5caed", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"value": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 262], "lh_t": [0, 0, 2], "dn_t": [0, 0, 2], "xp_t": [0, 38, 318], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tpscroll"}, {"time": -66.817, "key": "stout_shield"}, {"time": -66.417, "key": "enchanted_mango"}, {"time": -65.851, "key": "tango"}, {"time": -65.184, "key": "tango"}, {"time": -64.951, "key": "flask"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 713, "4": 196, "5": 1, "6": 3, "7": 18, "8": 2, "10": 52, "11": 2, "12": 1, "16": 5, "19": 1, "33": 52}, "pings": {}, "purchase": {"tpscroll": 1, "stout_shield": 1, "enchanted_mango": 1, "tango": 2, "flask": 1}, "gold_reasons": {"0": 600, "13": 164}, "xp_reasons": {"2": 478}, "killed": {"npc_dota_creep_goodguys_ranged": 113, "npc_dota_creep_badguys_melee": 281, "npc_dota_creep_goodguys_melee": 53}, "item_uses": {"tpscroll": 1, "enchanted_mango": 1, "flask": 1, "tango": 6}, "ability_uses": {"brewmaster_drunken_haze": 2}, "hero_hits": {}, "damage": {"npc_dota_creep_goodguys_ranged": 113, "npc_dota_creep_badguys_melee": 1002, "npc_dota_creep_goodguys_melee": 212}, "damage_taken": {"npc_dota_creep_badguys_melee": 148, "npc_dota_hero_tinker": 116}, "damage_inflictor": {}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {"npc_dota_hero_brewmaster": 1}, "damage_inflictor_received": {"null": 116}, "randomed": false, "pred_vict": false, "gold": 399, "lh": 4, "xp": 478, "x": 124, "y": 126, "hero_inventory": [], "hero_stash": [], "health": 636, "max_health": 720, "max_mana": 254.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 3, "nearby_creep_death_count": 19}, {"player_slot": 2, "hero_id": 14, "hero_name": "npc_dota_hero_pudge", "account_id_hash": "d0cb6c812472517b999025ea19d17b5c", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 123.437, "max": true, "inflictor": "pudge_rot", "unit": "npc_dota_hero_pudge", "key": "npc_dota_hero_ogre_magi", "value": 4, "slot": 2, "player_slot": 2}, "times": [0, 60, 120], "gold_t": [1, 91, 182], "lh_t": [0, 0, 0], "dn_t": [0, 0, 0], "xp_t": [0, 0, 73], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tpscroll"}, {"time": -70.849, "key": "courier"}, {"time": -69.116, "key": "tango"}, {"time": -65.117, "key": "magic_stick"}, {"time": -19.662, "key": "wind_lace"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 139.333, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 145, "5": 1, "7": 3, "8": 1, "9": 1, "10": 10, "11": 1, "15": 1, "16": 4, "19": 3, "33": 10}, "pings": {"0": 1}, "purchase": {"tpscroll": 1, "courier": 1, "tango": 1, "magic_stick": 1, "wind_lace": 1}, "gold_reasons": {"0": 669, "1": -67}, "xp_reasons": {"2": 130}, "killed": {}, "item_uses": {"courier": 1, "tango": 3, "tpscroll": 1}, "ability_uses": {"pudge_rot": 1}, "hero_hits": {"pudge_rot": 8}, "damage": {"npc_dota_hero_ogre_magi": 16, "npc_dota_hero_pudge": 16}, "damage_taken": {"npc_dota_hero_ogre_magi": 868, "npc_dota_hero_phantom_lancer": 224, "npc_dota_hero_pudge": 16}, "damage_inflictor": {"pudge_rot": 16}, "runes": {"5": 1}, "killed_by": {"npc_dota_hero_ogre_magi": 1}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 300, "1": 3, "2": 7}, "healing": {}, "damage_inflictor_received": {"null": 731, "orb_of_venom": 54, "ogre_magi_ignite": 190, "phantom_lancer_spirit_lance": 76, "ogre_magi_fireblast": 41}, "randomed": false, "pred_vict": false, "gold": 304, "lh": 0, "xp": 130, "x": 70, "y": 156, "hero_inventory": [{"id": "item_magic_stick", "num_charges": 4, "cooldown": 0}, {"id": "item_wind_lace", "cooldown": 0}], "hero_stash": [], "health": 700, "max_health": 700, "max_mana": 242.938, "level": 1, "kills": 0, "deaths": 1, "assists": 0, "denies": 0, "nearby_creep_death_count": 6}, {"player_slot": 3, "hero_id": 59, "hero_name": "npc_dota_hero_huskar", "account_id_hash": "83975f1afb5f5e97dc7266402f997dc3", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 83.48, "max": true, "inflictor": null, "unit": "npc_dota_hero_huskar", "key": "npc_dota_hero_night_stalker", "value": 42, "slot": 3, "player_slot": 3}, "times": [0, 60, 120], "gold_t": [1, 169, 260], "lh_t": [0, 2, 2], "dn_t": [0, 1, 1], "xp_t": [0, 202, 301], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "wind_lace"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "tpscroll"}, {"time": 52.221, "key": "magic_wand"}, {"time": 52.221, "key": "magic_stick"}, {"time": 117.438, "key": "flask"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 1053, "2": 8, "3": 3, "4": 84, "6": 3, "7": 3, "8": 1, "10": 41, "11": 2, "16": 7, "19": 1, "20": 2, "33": 41}, "pings": {}, "purchase": {"tango": 1, "wind_lace": 1, "enchanted_mango": 1, "branches": 2, "tpscroll": 1, "magic_wand": 1, "magic_stick": 1, "flask": 1}, "gold_reasons": {"0": 600, "13": 154}, "xp_reasons": {"2": 506}, "killed": {"npc_dota_creep_badguys_melee": 185, "npc_dota_creep_goodguys_melee": 46}, "item_uses": {"tango": 3}, "ability_uses": {}, "hero_hits": {"huskar_burning_spear": 25, "null": 6}, "damage": {"npc_dota_creep_badguys_melee": 497, "npc_dota_hero_huskar": 90, "npc_dota_hero_windrunner": 64, "npc_dota_creep_goodguys_melee": 46, "npc_dota_hero_night_stalker": 303}, "damage_taken": {"npc_dota_hero_windrunner": 402, "npc_dota_hero_night_stalker": 635, "npc_dota_hero_huskar": 90, "npc_dota_creep_badguys_melee": 65}, "damage_inflictor": {"null": 194, "huskar_burning_spear": 173}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"null": 760, "orb_of_venom": 87, "night_stalker_void": 190}, "randomed": false, "pred_vict": false, "gold": 389, "lh": 4, "xp": 506, "x": 170, "y": 86, "hero_inventory": [{"id": "item_wind_lace", "cooldown": 0}, {"id": "item_magic_wand", "num_charges": 2, "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 399, "max_health": 700, "max_mana": 326.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 1, "nearby_creep_death_count": 14}, {"player_slot": 4, "hero_id": 77, "hero_name": "npc_dota_hero_lycan", "account_id_hash": "7713505172bca930266a2da3524ae04e", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 0, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"value": 0}, "times": [0, 60, 120], "gold_t": [1, 91, 281], "lh_t": [0, 0, 5], "dn_t": [0, 0, 0], "xp_t": [0, 38, 238], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "stout_shield"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "faerie_fire"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": -9.198, "key": "quelling_blade"}], "kills_log": [], "buyback_log": [], "runes_log": [], "obs": {}, "sen": {}, "actions": {"1": 671, "2": 5, "3": 1, "4": 130, "7": 1, "8": 1, "10": 1, "11": 2, "16": 4, "19": 2}, "pings": {}, "purchase": {"stout_shield": 1, "branches": 2, "faerie_fire": 1, "enchanted_mango": 1, "tpscroll": 1, "quelling_blade": 1}, "gold_reasons": {"0": 600, "13": 167}, "xp_reasons": {"2": 344}, "killed": {"npc_dota_neutral_satyr_soulstealer": 174, "npc_dota_neutral_satyr_trickster": 194, "npc_dota_neutral_mud_golem": 209, "npc_dota_neutral_mud_golem_split": 399}, "item_uses": {"quelling_blade": 1}, "ability_uses": {"lycan_howl": 1}, "hero_hits": {}, "damage": {"npc_dota_neutral_satyr_soulstealer": 1286, "npc_dota_neutral_satyr_trickster": 780, "npc_dota_neutral_mud_golem": 1721, "npc_dota_neutral_mud_golem_split": 1206, "npc_dota_neutral_giant_wolf": 97}, "damage_taken": {"npc_dota_neutral_satyr_soulstealer": 227, "npc_dota_neutral_satyr_trickster": 56, "npc_dota_neutral_mud_golem": 343, "npc_dota_neutral_mud_golem_split": 44, "npc_dota_neutral_giant_wolf": 35}, "damage_inflictor": {}, "runes": {}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {}, "randomed": true, "pred_vict": false, "gold": 402, "lh": 10, "xp": 344, "x": 120, "y": 100, "hero_inventory": [{"id": "item_stout_shield", "cooldown": 0}, {"id": "item_quelling_blade", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}, {"id": "item_faerie_fire", "num_charges": 1, "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}], "hero_stash": [], "health": 422, "max_health": 800, "max_mana": 314.938, "level": 2, "kills": 0, "deaths": 0, "assists": 0, "denies": 0, "nearby_creep_death_count": 12}, {"player_slot": 128, "hero_id": 12, "hero_name": "npc_dota_hero_phantom_lancer", "account_id_hash": "c5e8f264da8fbb8b352f5298039c9be8", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 1, "firstblood_claimed": 0, "teamfight_participation": 1, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": 118.771, "max": true, "inflictor": "phantom_lancer_spirit_lance", "unit": "npc_dota_hero_phantom_lancer", "key": "npc_dota_hero_pudge", "value": 76, "slot": 5, "player_slot": 128}, "times": [0, 60, 120], "gold_t": [1, 331, 738], "lh_t": [0, 2, 9], "dn_t": [0, 4, 12], "xp_t": [0, 85, 431], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "flask"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "stout_shield"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": 23.428, "key": "quelling_blade"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 4.232, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 443, "2": 12, "3": 1, "4": 80, "6": 1, "7": 4, "10": 19, "11": 2, "15": 2, "16": 7, "17": 1, "19": 5, "33": 19}, "pings": {}, "purchase": {"tango": 1, "flask": 1, "branches": 1, "stout_shield": 1, "enchanted_mango": 1, "tpscroll": 1, "quelling_blade": 1}, "gold_reasons": {"0": 760, "12": 34, "13": 553}, "xp_reasons": {"1": 30, "2": 750}, "killed": {"npc_dota_creep_badguys_melee": 507, "npc_dota_creep_goodguys_melee": 648, "npc_dota_creep_badguys_ranged": 239, "npc_dota_creep_goodguys_ranged": 364}, "item_uses": {"tango": 1, "quelling_blade": 3}, "ability_uses": {"phantom_lancer_spirit_lance": 1}, "hero_hits": {"phantom_lancer_spirit_lance": 1, "null": 4}, "damage": {"npc_dota_creep_badguys_melee": 695, "npc_dota_creep_goodguys_melee": 1436, "npc_dota_creep_badguys_ranged": 239, "npc_dota_creep_goodguys_ranged": 927, "npc_dota_hero_pudge": 224}, "damage_taken": {"npc_dota_creep_goodguys_ranged": 220, "npc_dota_creep_goodguys_melee": 127}, "damage_inflictor": {"phantom_lancer_spirit_lance": 76, "null": 148}, "runes": {"5": 1}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {}, "randomed": false, "pred_vict": true, "gold": 982, "lh": 12, "xp": 780, "x": 82, "y": 170, "hero_inventory": [{"id": "item_tango", "num_charges": 2, "cooldown": 0}, {"id": "item_flask", "num_charges": 1, "cooldown": 0}, {"id": "item_enchanted_mango", "cooldown": 0}, {"id": "item_stout_shield", "cooldown": 0}, {"id": "item_quelling_blade", "cooldown": 0}, {"id": "item_branches", "cooldown": 0}], "hero_stash": [], "health": 650, "max_health": 720, "max_mana": 386.938, "level": 3, "kills": 0, "deaths": 0, "assists": 1, "denies": 13, "nearby_creep_death_count": 30}, {"player_slot": 129, "hero_id": 21, "hero_name": "npc_dota_hero_windrunner", "account_id_hash": "0472e177a478eb381f3534446f80cd2a", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 2, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0, "stuns": 0, "max_hero_hit": {"type": "max_hero_hit", "time": -5.465, "max": true, "inflictor": null, "unit": "npc_dota_hero_windrunner", "key": "npc_dota_hero_huskar", "value": 50, "slot": 6, "player_slot": 129}, "times": [0, 60, 120], "gold_t": [1, 251, 561], "lh_t": [0, 0, 5], "dn_t": [0, 1, 4], "xp_t": [0, 58, 445], "obs_log": [], "sen_log": [], "obs_left_log": [], "sen_left_log": [], "purchase_log": [{"time": -89.783, "key": "orb_of_venom"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "tango"}, {"time": -89.783, "key": "branches"}, {"time": -89.783, "key": "enchanted_mango"}, {"time": -89.783, "key": "tpscroll"}, {"time": 23.428, "key": "magic_wand"}, {"time": 23.428, "key": "magic_stick"}], "kills_log": [], "buyback_log": [], "runes_log": [{"time": 1.7, "key": 5}, {"time": 8.565, "key": 5}], "obs": {}, "sen": {}, "actions": {"1": 575, "2": 4, "4": 77, "11": 3, "15": 10, "16": 6, "19": 3}, "pings": {}, "purchase": {"orb_of_venom": 1, "branches": 2, "tango": 1, "enchanted_mango": 1, "tpscroll": 1, "magic_wand": 1, "magic_stick": 1}, "gold_reasons": {"0": 760, "13": 393}, "xp_reasons": {"2": 706}, "killed": {"npc_dota_creep_badguys_ranged": 159, "npc_dota_creep_goodguys_melee": 350, "npc_dota_creep_badguys_melee": 148, "npc_dota_creep_goodguys_ranged": 110}, "item_uses": {}, "ability_uses": {}, "hero_hits": {"null": 8, "orb_of_venom": 14}, "damage": {"npc_dota_hero_huskar": 402, "npc_dota_creep_goodguys_melee": 460, "npc_dota_creep_badguys_ranged": 265, "npc_dota_creep_badguys_melee": 740, "npc_dota_creep_goodguys_ranged": 110}, "damage_taken": {"npc_dota_hero_huskar": 64, "npc_dota_creep_goodguys_melee": 95, "npc_dota_creep_goodguys_ranged": 31}, "damage_inflictor": {"null": 360, "orb_of_venom": 42}, "runes": {"5": 2}, "killed_by": {}, "kill_streaks": {}, "multi_kills": {}, "life_state": {"0": 310}, "healing": {}, "damage_inflictor_received": {"null": 40, "huskar_burning_spear": 24}, "randomed": false, "pred_vict": true, "gold": 788, "lh": 9, "xp": 706, "x": 174, "y": 90, "hero_inventory": [{"id": "item_orb_of_venom", "cooldown": 0}, {"id": "item_tango", "num_charges": 3, "cooldown": 0}, {"id": "item_flask", "num_charges": 1, "cooldown": 0}, {"id": "item_magic_wand", "cooldown": 0}, {"id": "item_tpscroll", "num_charges": 1, "cooldown": 0}], "hero_stash": [], "health": 640, "max_health": 640, "max_mana": 422.938, "level": 3, "kills": 0, "deaths": 0, "assists": 0, "denies": 6, "nearby_creep_death_count": 23}, {"player_slot": 130, "hero_id": 60, "hero_name": "npc_dota_hero_night_stalker", "account_id_hash": "fc1271b29e684b9e7f39817b94db73dd", "ability_upgrades": [], "obs_placed": 0, "sen_placed": 0, "creeps_stacked": 0, "camps_stacked": 0, "rune_pickups": 2, "firstblood_claimed": 0, "teamfight_participation": 0, "towers_killed": 0, "roshans_killed": 0, "observers_placed": 0

In [12]:
import json

src = "DOTA 2//train_matches.jsonl"
dst = "train_matches_sample.jsonl"

step = 1000  # каждую сотую строку берём в семпл

with open(src, "r", encoding="utf-8") as fin, \
     open(dst, "w", encoding="utf-8") as fout:
    for i, line in enumerate(fin, start=1):
        if not line.strip():
            continue
        if i % step == 0:
            fout.write(line)

print("Готово, семпл сохранён в", dst)

Готово, семпл сохранён в train_matches_sample.jsonl

In [13]:
df = pd.read_json("train_matches_sample.jsonl", lines=True)
df.head()

,game_time,match_id_hash,teamfights,objectives,chat,game_mode,lobby_type,players,targets
0,1697,fd0f070411e0ef7ea846ce08f3c9fdd9,"[{'start': 769.229, 'end': 812.156, 'last_deat...","[{'time': 342.937, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 0, 'time': -59.346, 'text': '...",4,0,"[{'player_slot': 0, 'hero_id': 31, 'hero_name'...","{'game_time': 1697, 'duration': 2079, 'time_re..."
1,1803,9e30e8cfcedb1d729bfb12aa6890de32,"[{'start': 1699.781, 'end': 1754.172, 'last_de...","[{'time': 203.984, 'type': 'CHAT_MESSAGE_FIRST...","[{'player_slot': 4, 'time': 167.992, 'text': '...",22,0,"[{'player_slot': 0, 'hero_id': 34, 'hero_name'...","{'game_time': 1803, 'duration': 2091, 'time_re..."
2,1104,777b1b4b7a8f876a8f6ed21254d10558,"[{'start': 454.552, 'end': 498.412, 'last_deat...","[{'time': 80.214, 'type': 'CHAT_MESSAGE_FIRSTB...","[{'player_slot': 1, 'time': 123.637, 'text': '...",23,0,"[{'player_slot': 0, 'hero_id': 98, 'hero_name'...","{'game_time': 1104, 'duration': 1340, 'time_re..."
3,728,0080cf7fc113814c984a18007d5260c1,"[{'start': 268.397, 'end': 339.984, 'last_deat...","[{'time': 203.484, 'type': 'CHAT_MESSAGE_FIRST...",[],22,7,"[{'player_slot': 0, 'hero_id': 57, 'hero_name'...","{'game_time': 728, 'duration': 1799, 'time_rem..."
4,541,79629858b12e9d2f0685a8dc6fe0efc9,"[{'start': 415.539, 'end': 467.596, 'last_deat...","[{'time': 85.618, 'type': 'CHAT_MESSAGE_FIRSTB...","[{'player_slot': 2, 'time': 7.9350000000000005...",23,0,"[{'player_slot': 0, 'hero_id': 4, 'hero_name':...","{'game_time': 541, 'duration': 1004, 'time_rem..."

In [14]:
df.shape

(33, 9)

In [33]:
df.iloc[6]['players']

[{'player_slot': 0,
  'hero_id': 32,
  'hero_name': 'npc_dota_hero_riki',
  'account_id_hash': '9c531e504bf2d730a4e7ae7fb2e1c8e1',
  'ability_upgrades': [{'ability': 5144, 'time': 298, 'level': 1},
   {'ability': 5143, 'time': 568, 'level': 2},
   {'ability': 5144, 'time': 704, 'level': 3},
   {'ability': 5142, 'time': 847, 'level': 4},
   {'ability': 5144, 'time': 987, 'level': 5},
   {'ability': 5145, 'time': 1091, 'level': 6},
   {'ability': 5144, 'time': 1146, 'level': 7},
   {'ability': 5143, 'time': 1232, 'level': 8},
   {'ability': 5143, 'time': 1305, 'level': 9},
   {'ability': 6014, 'time': 1421, 'level': 10},
   {'ability': 5143, 'time': 1476, 'level': 11},
   {'ability': 5145, 'time': 1557, 'level': 12},
   {'ability': 5142, 'time': 1603, 'level': 13},
   {'ability': 5142, 'time': 1722, 'level': 14},
   {'ability': 7045, 'time': 1923, 'level': 15},
   {'ability': 5142, 'time': 1952, 'level': 16}],
  'obs_placed': 1,
  'sen_placed': 1,
  'creeps_stacked': 0,
  'camps_stacked': 0,
  'rune_pickups': 14,
  'firstblood_claimed': 0,
  'teamfight_participation': 0.538,
  'towers_killed': 0,
  'roshans_killed': 0,
  'observers_placed': 1,
  'stuns': 7.654,
  'max_hero_hit': {'type': 'max_hero_hit',
   'time': 1812.296,
   'max': True,
   'inflictor': None,
   'unit': 'npc_dota_hero_riki',
   'key': 'npc_dota_hero_invoker',
   'value': 292,
   'slot': 0,
   'player_slot': 0},
  'times': [0,
   60,
   120,
   180,
   240,
   300,
   360,
   420,
   480,
   540,
   600,
   660,
   720,
   780,
   840,
   900,
   960,
   1020,
   1080,
   1140,
   1200,
   1260,
   1320,
   1380,
   1440,
   1500,
   1560,
   1620,
   1680,
   1740,
   1800,
   1860,
   1920,
   1980],
  'gold_t': [41,
   171,
   262,
   589,
   680,
   825,
   970,
   1289,
   1380,
   1675,
   1982,
   2292,
   2565,
   2935,
   3387,
   3762,
   4474,
   4689,
   5180,
   5663,
   6244,
   6679,
   6770,
   7471,
   8040,
   8192,
   8554,
   9152,
   9383,
   9474,
   9565,
   9924,
   10743,
   11563],
  'lh_t': [0,
   0,
   0,
   1,
   1,
   1,
   1,
   2,
   2,
   2,
   7,
   9,
   12,
   14,
   15,
   16,
   16,
   16,
   16,
   24,
   25,
   25,
   25,
   27,
   28,
   30,
   37,
   37,
   40,
   40,
   40,
   40,
   48,
   51],
  'dn_t': [0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   0,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2,
   2],
  'xp_t': [0,
   35,
   70,
   188,
   347,
   515,
   737,
   919,
   1102,
   1244,
   1598,
   1935,
   2558,
   2951,
   3549,
   3857,
   4738,
   4766,
   5812,
   6503,
   7332,
   8233,
   8347,
   9374,
   9780,
   9860,
   10902,
   12089,
   12574,
   12574,
   12751,
   13096,
   14968,
   15391],
  'obs_log': [{'time': -30.692,
    'tick': 10369,
    'type': 'obs_log',
    'key': '[120, 138]',
    'slot': 0,
    'x': 120,
    'y': 138,
    'z': 130,
    'entityleft': False,
    'ehandle': 4440674,
    'player_slot': 0}],
  'sen_log': [{'time': 145.598,
    'tick': 15659,
    'type': 'sen_log',
    'key': '[82, 156]',
    'slot': 0,
    'x': 82,
    'y': 156,
    'z': 130,
    'entityleft': False,
    'ehandle': 1230118,
    'player_slot': 0}],
  'obs_left_log': [{'time': 335.118,
    'tick': 21346,
    'type': 'obs_left_log',
    'key': '[120, 138]',
    'slot': 0,
    'x': 120,
    'y': 138,
    'z': 130,
    'entityleft': True,
    'ehandle': 4440674,
    'player_slot': 0}],
  'sen_left_log': [{'time': 391.438,
    'tick': 23036,
    'type': 'sen_left_log',
    'key': '[82, 156]',
    'slot': 0,
    'x': 82,
    'y': 156,
    'z': 130,
    'entityleft': True,
    'ehandle': 1230118,
    'player_slot': 0}],
  'purchase_log': [{'time': -89.611, 'key': 'orb_of_venom'},
   {'time': -89.611, 'key': 'tango'},
   {'time': -89.611, 'key': 'stout_shield'},
   {'time': -89.611, 'key': 'tpscroll'},
   {'time': 13.797, 'key': 'ward_sentry'},
   {'time': 329.62, 'key': 'flask'},
   {'time': 512.542, 'key': 'gloves'},
   {'time': 523.139, 'key': 'blade_of_alacrity'},
   {'time': 679.467, 'key': 'blade_of_alacrity'},
   {'time': 680.734, 'key': 'tpscroll'},
   {'time': 765.08, 'key': 'robe'},
   {'time': 770.045, 'key': 'tpscroll'},
   {'time': 872.487, 'key': 'diffusal_blade'},
   {'time': 927.407, 'key': 'boots'},
   {'time': 976.295, 'key': 'gloves'},
   {'time': 977.761, 'key': 'tpscroll'},
   {'time': 996.357, 'key': 'tpscroll'},
   {'time': 1032.115, 'key': 'belt_of_strength'},
   {'time': 1039.313, 'key': 'power_treads'},
   {'time': 1072.971, 'key': 'tpscroll'},
   {'time': 1209.438, 'key': 'javelin'},
   {'time': 1238.731, 'key': 'belt_of_strength'},
   {'time': 1287.752, 'key': 'tpscroll'},
   {'time': 1466.242, 'key': 'basher'},
   {'time': 1512.664, 'key': 'tpscroll'},
   {'time': 1606.241, 'key': 'tpscroll'},
   {'time': 1673.256, 'key': 'blades_of_attack'},
   {'time': 1715.366, 'key': 'tpscroll'},
   {'time': 1851.095, 'key': 'tpscroll'},
   {'time': 1911.701, 'key': 'broadsword'},
   {'time': 1997.861, 'key': 'lesser_crit'}],
  'kills_log': [{'time': 759.748, 'key': 'npc_dota_hero_tiny'},
   {'time': 838.962, 'key': 'npc_dota_hero_rubick'},
   {'time': 890.682, 'key': 'npc_dota_hero_pudge'},
   {'time': 937.938, 'key': 'npc_dota_hero_rubick'},
   {'time': 1028.915, 'key': 'npc_dota_hero_tiny'},
   {'time': 1172.447, 'key': 'npc_dota_hero_invoker'},
   {'time': 1217.236, 'key': 'npc_dota_hero_rubick'},
   {'time': 1333.441, 'key': 'npc_dota_hero_faceless_void'},
   {'time': 1562.652, 'key': 'npc_dota_hero_faceless_void'},
   {'time': 1803.198, 'key': 'npc_dota_hero_tiny'},
   {'time': 1897.118, 'key': 'npc_dota_hero_tiny'}],
  'buyback_log': [],
  'runes_log': [{'time': 120.471, 'key': 5},
   {'time': 130.202, 'key': 5},
   {'time': 360.179, 'key': 5},
   {'time': 370.576, 'key': 5},
   {'time': 480.416, 'key': 5},
   {'time': 489.547, 'key': 5},
   {'time': 618.249, 'key': 0},
   {'time': 946.369, 'key': 5},
   {'time': 952.234, 'key': 5},
   {'time': 960.299, 'key': 5},
   {'time': 973.829, 'key': 1},
   {'time': 1320.311, 'key': 5},
   {'time': 1938.024, 'key': 5},
   {'time': 1943.71, 'key': 5}],
  'obs': {'120': {'138': 1}},
  'sen': {'82': {'156': 1}},
  'actions': {'1': 1804,
   '2': 32,
   '3': 2,
   '4': 381,
   '5': 45,
   '6': 66,
   '7': 2,
   '8': 50,
   '10': 46,
   '11': 15,
   '15': 39,
   '16': 29,
   '17': 2,
   '19': 14,
   '24': 2,
   '27': 10,
   '33': 46},
  'pings': {'0': 22},
  'purchase': {'orb_of_venom': 1,
   'tango': 1,
   'stout_shield': 1,
   'tpscroll': 11,
   'ward_sentry': 1,
   'flask': 1,
   'gloves': 2,
   'blade_of_alacrity': 2,
   'robe': 1,
   'recipe_diffusal_blade': 1,
   'diffusal_blade': 1,
   'boots': 1,
   'belt_of_strength': 2,
   'power_treads': 1,
   'javelin': 1,
   'basher': 1,
   'recipe_basher': 1,
   'blades_of_attack': 1,
   'recipe_lesser_crit': 1,
   'broadsword': 1,
   'lesser_crit': 1},
  'gold_reasons': {'0': 2164,
   '1': -1520,
   '6': 600,
   '11': 960,
   '12': 3702,
   '13': 2187,
   '14': 150},
  'xp_reasons': {'0': 51, '1': 8500, '2': 6505, '3': 336},
  'killed': {'npc_dota_observer_wards': 8,
   'npc_dota_creep_badguys_ranged': 1783,
   'npc_dota_creep_badguys_melee': 3413,
   'npc_dota_badguys_siege': 147,
   'npc_dota_hero_tiny': 512,
   'npc_dota_hero_rubick': 389,
   'npc_dota_hero_pudge': 53,
   'npc_dota_creep_goodguys_melee': 251,
   'npc_dota_hero_invoker': 148,
   'npc_dota_hero_faceless_void': 379,
   'npc_dota_neutral_ogre_magi': 143,
   'npc_dota_neutral_mud_golem': 285,
   'npc_dota_neutral_mud_golem_split': 570,
   'npc_dota_neutral_ogre_mauler': 95,
   'npc_dota_neutral_big_thunder_lizard': 165,
   'npc_dota_invoker_forged_spirit': 282,
   'npc_dota_neutral_gnoll_assassin': 636},
  'item_uses': {'ward_observer': 1,
   'ward_sentry': 1,
   'tango': 3,
   'flask': 1,
   'tpscroll': 10,
   'diffusal_blade': 18,
   'power_treads': 2},
  'ability_uses': {'riki_blink_strike': 30,
   'riki_smoke_screen': 23,
   'riki_tricks_of_the_trade': 12},
  'hero_hits': {'null': 153, 'orb_of_venom': 146, 'riki_blink_strike': 20},
  'damage': {'npc_dota_hero_rubick': 3678,
   'npc_dota_observer_wards': 8,
   'npc_dota_hero_faceless_void': 3937,
   'npc_dota_creep_goodguys_melee': 471,
   'npc_dota_creep_badguys_ranged': 3657,
   'npc_dota_creep_badguys_melee': 8403,
   'npc_dota_hero_tiny': 8044,
   'npc_dota_badguys_siege': 823,
   'npc_dota_hero_pudge': 3696,
   'npc_dota_badguys_tower1_mid': 95,
   'npc_dota_hero_invoker': 3096,
   'illusion_npc_dota_hero_pudge': 1760,
   'npc_dota_neutral_ogre_magi': 681,
   'npc_dota_neutral_mud_golem': 1827,
   'npc_dota_neutral_ogre_mauler': 1225,
   'npc_dota_neutral_mud_golem_split': 1144,
   'npc_dota_neutral_granite_golem': 1024,
   'npc_dota_neutral_big_thunder_lizard': 329,
   'npc_dota_roshan': 1315,
   'npc_dota_invoker_forged_spirit': 1577,
   'npc_dota_neutral_gnoll_assassin': 636},
  'damage_taken': {'npc_dota_hero_rubick': 1844,
   'npc_dota_creep_badguys_ranged': 277,
   'npc_dota_hero_invoker': 1642,
   'npc_dota_creep_badguys_melee': 174,
   'npc_dota_badguys_tower1_mid': 73,
   'npc_dota_hero_faceless_void': 1578,
   'npc_dota_hero_tiny': 1704,
   'npc_dota_hero_pudge': 2647,
   'npc_dota_badguys_tower2_bot': 146,
   'npc_dota_neutral_ogre_magi': 10,
   'npc_dota_neutral_mud_golem': 107,
   'npc_dota_neutral_ogre_mauler': 141,
   'npc_dota_neutral_mud_golem_split': 58,
   'npc_dota_neutral_big_thunder_lizard': 67,
   'npc_dota_neutral_small_thunder_lizard': 28,
   'npc_dota_roshan': 814,
   'npc_dota_badguys_tower2_top': 556,
   'npc_dota_badguys_siege': 81,
   'npc_dota_neutral_gnoll_assassin': 34,
   'dota_unknown': 1,
   'npc_dota_badguys_tower3_top': 66},
  'damage_inflictor': {'null': 20888,
   'orb_of_venom': 438,
   'riki_blink_strike': 1125},
  'runes': {'0': 1, '1': 1, '5': 12},
  'killed_by': {'npc_dota_hero_rubick': 1,
   'npc_dota_hero_pudge': 2,
   'npc_dota_hero_invoker': 2,
   'npc_dota_hero_faceless_void': 1},
  'kill_streaks': {'3': 1, '4': 1, '5': 1},
  'multi_kills': {},
  'life_state': {'0': 3469, '1': 18, '2': 559},
  'healing': {'npc_dota_hero_riki': 255},
  'damage_inflictor_received': {'null': 2713,
   'rubick_fade_bolt': 844,
   'tiny_avalanche': 774,
   'tiny_toss': 539,
   'invoker_cold_snap': 55,
   'sniper_assassinate': 246,
   'pudge_meat_hook': 1375,
   'pudge_rot': 736,
   'weaver_shukuchi': 244,
   'razor_plasma_field': 57,
   'pudge_dismember': 369,
   'invoker_sun_strike': 576,
   'invoker_tornado': 237,
   'disruptor_thunder_strike': 184,
   'tiny_craggy_exterior': 149,
   'invoker_deafening_blast': 317},
  'randomed': False,
  'pred_vict': True,
  'gold': 11628,
  'lh': 51,
  'xp': 15391,
  'x': 140,
  'y': 170,
  'hero_inventory': [{'id': 'item_diffusal_blade', 'cooldown': 0},
   {'id': 'item_tpscroll', 'num_charges': 1, 'cooldown': 0},
   {'id': 'item_lesser_crit', 'cooldown': 0},
   {'id': 'item_basher', 'cooldown': 0},
   {'id': 'item_power_treads', 'cooldown': 0, 'stat': 2},
   {'id': 'item_orb_of_venom', 'cooldown': 0}],
  'hero_stash': [],
  'health': 0,
  'max_health': 1380,
  'max_mana': 626.938,
  'level': 18,
  'kills': 11,
  'deaths': 6,
  'assists': 10,
  'denies': 2,
  'nearby_creep_death_count': 199},
 {'player_slot': 1,
  'hero_id': 35,
  'hero_name': 'npc_dota_hero_sniper',
  'account_id_hash': '1c2500195e6ab646fc9371344724aa77',
  'ability_upgrades': [{'ability': 5155, 'time': 390, 'level': 1},
   {'ability': 5156, 'time': 446, 'level': 2},
   {'ability': 5154, 'time': 522, 'level': 3},
   {'ability': 5154, 'time': 580, 'level': 4},
   {'ability': 5154, 'time': 672, 'level': 5},
   {'ability': 5157, 'time': 736, 'level': 6},
   {'ability': 5154, 'time': 834, 'level': 7},
   {'ability': 5156, 'time': 951, 'level': 8},
   {'ability': 5156, 'time': 1070, 'level': 9},
   {'ability': 5960, 'time': 1178, 'level': 10},
   {'ability': 5156, 'time': 1275, 'level': 11},
   {'ability': 5157, 'time': 1418, 'level': 12},
   {'ability': 5155, 'time': 1447, 'level': 13},
   {'ability': 5155, 'time': 1628, 'level': 14},
   {'ability': 6210, 'time': 1755, 'level': 15},
   {'ability': 5155, 'time': 1793, 'level': 16},
   {'ability': 5157, 'time': 2021, 'level': 17}],
  'obs_placed': 0,
  'sen_placed': 0,
  'creeps_stacked': 1,
  'camps_stacked': 1,
  'rune_pickups': 2,
  'firstblood_claimed': 1,
  'teamfight_participation': 0.744,
  'towers_killed': 5,
  'roshans_killed': 1,
  'observers_placed': 0,
  'stuns': 0.2,
  'max_hero_hit': {'type': 'max_hero_hit',
   'time': 1700.281,
   'max': True,
   'inflictor': None,
   'unit': 'npc_dota_hero_sniper',
   'key': 'npc_dota_hero_rubick',
   'value': 503,
   'slot': 1,
   'player_slot': 1},
  'times': [0,
   60,
   120,
   180,
   240,
   300,
   360,
   420,
   480,
   540,
   600,
   660,
   720,
   780,
   840,
   900,
   960,
   1020,
   1080,
   1140,
   1200,
   1260,
   1320,
   1380,
   1440,
   1500,
   1560,
   1620,
   1680,
   1740,
   1800,
   1860,
   1920,
   1980],
  'gold_t': [41,
   227,
   550,
   1207,
   1565,
   1877,
   2304,
   2687,
   3048,
   3319,
   4110,
   4574,
   4771,
   5121,
   5539,
   5948,
   6890,
   7211,
   7982,
   8073,
   8675,
   9295,
   9386,
   10120,
   11234,
   11325,
   12268,
   13016,
   13277,
   13966,
   14264,
   14972,
   15862,
   16784],
  'lh_t': [0,
   1,
   6,
   11,
   17,
   21,
   24,
   31,
   37,
   41,
   52,
   57,
   60,
   65,
   67,
   73,
   84,
   89,
   93,
   93,
   98,
   103,
   103,
   112,
   119,
   119,
   126,
   130,
   134,
   141,
   146,
   151,
   166,
   175],
  'dn_t': [0,
   0,
   0,
   1,
   2,
   6,
   8,
   12,
   12,
   13,
   14,
   14,
   15,
   15,
   15,
   15,
   15,
   15,
   15,
   15,
   15,
   15,
   15,
   16,
   16,
   16,
   16,
   16,
   16,
   16,
   16,
   16,
   16,
   16],
  'xp_t': [0,
   176,
   484,
   939,
   1347,
   1843,
   2372,
   2862,
   3117,
   3423,
   3924,
   4187,
   4497,
   4954,
   5516,
   6006,
   6309,
   6661,
   7815,
   7815,
   8066,
   8906,
   8906,
   10897,
   12051,
   12051,
   13151,
   13892,
   14197,
   15102,
   15245,
   16370,
   17827,
   18786],
  'obs_log': [],
  'sen_log': [],
  'obs_left_log': [],
  'sen_left_log': [],
  'purchase_log': [{'time': -89.611, 'key': 'tango'},
   {'time': -89.611, 'key': 'wraith_band'},
   {'time': -89.611, 'key': 'tpscroll'},
   {'time': 54.82, 'key': 'magic_stick'},
   {'time': 167.726, 'key': 'boots'},
   {'time': 186.055, 'key': 'sobi_mask'},
   {'time': 186.188, 'key': 'ring_of_basilius'},
   {'time': 186.188, 'key': 'ring_of_protection'},
   {'time': 187.021, 'key': 'branches'},
   {'time': 199.785, 'key': 'branches'},
   {'time': 200.018, 'key': 'enchanted_mango'},
   {'time': 225.778, 'key': 'magic_wand'},
   {'time': 225.778, 'key': 'ring_of_aquila'},
   {'time': 291.662, 'key': 'blades_of_attack'},
   {'time': 355.68, 'key': 'blades_of_attack'},
   {'time': 413.399, 'key': 'phase_boots'},
   {'time': 525.105, 'key': 'ogre_axe'},
   {'time': 580.558, 'key': 'boots_of_elves'},
   {'time': 592.755, 'key': 'boots_of_elves'},
   {'time': 622.948, 'key': 'dragon_lance'},
   {'time': 861.256, 'key': 'shadow_amulet'},
   {'time': 955.233, 'key': 'invis_sword'},
   {'time': 955.233, 'key': 'claymore'},
   {'time': 1146.72, 'key': 'tpscroll'},
   {'time': 1204.373, 'key': 'mithril_hammer'},
   {'time': 1263.358, 'key': 'blight_stone'},
   {'time': 1319.978, 'key': 'tpscroll'},
   {'time': 1414.121, 'key': 'mithril_hammer'},
   {'time': 1430.584, 'key': 'flask'},
   {'time': 1498.467, 'key': 'desolator'},
   {'time': 1731.722, 'key': 'staff_of_wizardry'},
   {'time': 1732.223, 'key': 'ring_of_health'},
   {'time': 1732.725, 'key': 'force_staff'},
   {'time': 1813.065, 'key': 'hurricane_pike'},
   {'time': 1926.753, 'key': 'mithril_hammer'},
   {'time': 1926.953, 'key': 'gloves'},
   {'time': 1927.154, 'key': 'maelstrom'}],
  'kills_log': [{'time': 154.729, 'key': 'npc_dota_hero_tiny'},
   {'time': 352.481, 'key': 'npc_dota_hero_tiny'},
   {'time': 582.958, 'key': 'npc_dota_hero_tiny'},
   {'time': 789.207, 'key': 'npc_dota_hero_invoker'},
   {'time': 1033.848, 'key': 'npc_dota_hero_pudge'},
   {'time': 1048.677, 'key': 'npc_dota_hero_invoker'},
   {'time': 1235.698, 'key': 'npc_dota_hero_tiny'},
   {'time': 1538.158, 'key': 'npc_dota_hero_invoker'},
   {'time': 1555.387, 'key': 'npc_dota_hero_rubick'},
   {'time': 1704.295, 'key': 'npc_dota_hero_rubick'},
   {'time': 1844.64, 'key': 'npc_dota_hero_invoker'}],
  'buyback_log': [],
  'runes_log': [{'time': 823.666, 'key': 6}, {'time': 1712.055, 'key': 4}],
  'obs': {},
  'sen': {},
  'actions': {'1': 3079,
   '3': 134,
   '4': 1204,
   '5': 40,
   '6': 19,
   '7': 3,
   '8': 91,
   '9': 2,
   '10': 43,
   '11': 15,
   '14': 6,
   '15': 8,
   '16': 30,
   '18': 1,
   '19': 17,
   '27': 1,
   '32': 1,
   '33': 43},
  'pings': {'0': 9},
  'purchase': {'tango': 1,
   'wraith_band': 1,
   'tpscroll': 3,
   'magic_stick': 1,
   'boots': 1,
   'sobi_mask': 1,
   'ring_of_basilius': 1,
   'ring_of_protection': 1,
   'branches': 2,
   'enchanted_mango': 1,
   'magic_wand': 1,
   'ring_of_aquila': 1,
   'blades_of_attack': 2,
   'phase_boots': 1,
   'ogre_axe': 1,
   'boots_of_elves': 2,
   'dragon_lance': 1,
   'shadow_amulet': 1,
   'invis_sword': 1,
   'claymore': 1,
   'mithril_hammer': 3,
   'blight_stone': 1,
   'flask': 1,
   'desolator': 1,
   'staff_of_wizardry': 1,
   'ring_of_health': 1,
   'force_staff': 1,
   'recipe_force_staff': 1,
   'hurricane_pike': 1,
   'gloves': 1,
   'maelstrom': 1,
   'recipe_maelstrom': 1},
  'gold_reasons': {'0': 680,
   '1': -1337,
   '11': 1846,
   '12': 3579,
   '13': 7790,
   '14': 489},
  'xp_reasons': {'0': 57, '1': 9456, '2': 8944, '3': 336},
  'killed': {'npc_dota_creep_badguys_ranged': 5181,
   'npc_dota_creep_badguys_melee': 19221,
   'npc_dota_creep_goodguys_melee': 828,
   'npc_dota_hero_tiny': 456,
   'npc_dota_creep_goodguys_ranged': 342,
   'npc_dota_badguys_siege': 423,
   'npc_dota_neutral_satyr_trickster': 115,
   'npc_dota_neutral_satyr_soulstealer': 109,
   'npc_dota_hero_invoker': 862,
   'npc_dota_badguys_tower1_top': 33,
   'npc_dota_hero_pudge': 247,
   'npc_dota_badguys_tower1_mid': 42,
   'npc_dota_goodguys_tower1_bot': 49,
   'npc_dota_neutral_dark_troll': 263,
   'npc_dota_neutral_dark_troll_warlord': 324,
   'npc_dota_badguys_tower2_bot': 38,
   'npc_dota_neutral_ogre_mauler': 276,
   'npc_dota_neutral_rock_golem': 592,
   'npc_dota_neutral_granite_golem': 209,
   'npc_dota_invoker_forged_spirit': 77,
   'npc_dota_neutral_small_thunder_lizard': 396,
   'npc_dota_hero_rubick': 633,
   'npc_dota_roshan': 147,
   'npc_dota_neutral_polar_furbolg_ursa_warrior': 330,
   'npc_dota_neutral_polar_furbolg_champion': 245,
   'npc_dota_neutral_centaur_outrunner': 625,
   'npc_dota_badguys_tower2_top': 56},
  'item_uses': {'ring_of_aquila': 2,
   'phase_boots': 58,
   'magic_wand': 3,
   'tango': 3,
   'tpscroll': 3,
   'invis_sword': 8,
   'flask': 1,
   'hurricane_pike': 2},
  'ability_uses': {'sniper_shrapnel': 31, 'sniper_assassinate': 11},
  'hero_hits': {'null': 150, 'sniper_shrapnel': 83, 'sniper_assassinate': 9},
  'damage': {'npc_dota_hero_tiny': 9099,
   'npc_dota_creep_goodguys_melee': 2169,
   'npc_dota_creep_badguys_melee': 49063,
   'npc_dota_creep_badguys_ranged': 11689,
   'npc_dota_creep_goodguys_ranged': 501,
   'npc_dota_hero_rubick': 6182,
   'npc_dota_goodguys_siege': 116,
   'npc_dota_badguys_siege': 3396,
   'npc_dota_badguys_tower1_bot': 888,
   'npc_dota_hero_pudge': 2414,
   'npc_dota_neutral_satyr_trickster': 115,
   'npc_dota_neutral_satyr_soulstealer': 230,
   'npc_dota_badguys_tower1_mid': 752,
   'npc_dota_hero_invoker': 5287,
   'npc_dota_badguys_tower1_top': 840,
   'npc_dota_hero_faceless_void': 2135,
   'npc_dota_badguys_tower2_bot': 1166,
   'npc_dota_badguys_tower2_mid': 580,
   'npc_dota_goodguys_tower1_bot': 49,
   'npc_dota_neutral_dark_troll': 494,
   'npc_dota_neutral_dark_troll_warlord': 324,
   'npc_dota_neutral_wildkin': 181,
   'npc_dota_neutral_ogre_mauler': 660,